### ISSUE TITLE
Multi Robot Lanes

### ISSUE THREAD

**Issue by wzli** [tuw-robotics/tuw_multi_robot#2]
Hi,
First I'd like to say thanks for open-sourcing your MRRP implementation and contributing to the ROS environment. I'm currently testing different options for warehouse robot path planning, and this projects seems very promising. We are working with real robots, so the proof of concept has to be practical. One caveat for my scenario is that the width of some of the paths through the test environment is relatively wide compared to the size of the bots, so the constraint that only one robot may pass through a "vertex" at a time doesn't always hold and should ideally be a function of the width of the path segment instead. Are there any suggestions on how to incorporate this into the system? I can potentially contribute towards this if it isn't too paramount.

**Comment by maxbader** [comment]
Hi

Actually it is allready implemented. If the graph is generated by a voronoi we compute the free space next to each segments. It is also used by the mrrp because the graph keeps that information and each vehicle must have a defined radius.
But it is still work in progress. If you are interested I will be next week at the IROS and ROSCon.
By the way we are using it already on real robots and we have a gazebo simulation.

Greetings Markus



Von meinem Samsung Gerät gesendet.


-------- Ursprüngliche Nachricht --------
Von: wzli <notifications@github.com>
Datum: 28.09.18 11:54 (GMT+01:00)
An: tuw-robotics/tuw_multi_robot <tuw_multi_robot@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [tuw-robotics/tuw_multi_robot] Multi Robot Lanes (#2)


Hi,
First I'd like to say thanks for open-sourcing your MRRP implementation and contributing to the ROS environment. I'm currently testing different options for warehouse robot path planning, and this projects seems very promising. We are working with real robots, so the proof of concept has to be practical. One caveat for my scenario is that the width of some of the paths through the test environment is relatively wide compared to the size of the bots, so the constraint that only one robot may pass through a "vertex" at a time doesn't always hold and should ideally be a function of the width of the path segment instead. Are there any suggestions on how to incorporate this into the system? I can potentially contribute towards this if it isn't too paramount.

-

**Comment by maxbader** [comment]
Be aware that I published yesterday minor changes on the graph generation. The graph should be smoother have a look at the map_invlation parameter.
